name: Build and Deploy node Express app to azure
on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: "DCT"    # set this to your application's name
  AZURE_WEBAPP_NAME_PRD: "OfficialBaseTech"    # set this for name of production API
  AZURE_WEBAPP_PACKAGE_PATH: "Application"      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.16.0'                        # set this to the node version to use
  RESOURCEGROUPNAME: "DCT-rg"
  LOCATION: "South Central US"
  HOSTINGPLANNAME: "DCT-plan"
  APPINSIGHTLOCATION: "Brazil Southeast"
  SKU: "F1 Free"

jobs:
  build:
    name: Build and Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install and build
      continue-on-error: false
      run: |
        cd Application
        npm install
        npm run build --if-present
        
    - name: Creating artifact directories
      run: |
        mkdir buildartifacts

    # Archive build artifact
    - name: Archive Application
      run: |
        zip -qq -r ./buildartifacts/Application.zip ./Application

    # Uploading application to build artifact
    - name: Upload Application to Build Artifact
      continue-on-error: false
      uses: actions/upload-artifact@v2
      with:
        name: buildartifacts
        path: buildartifacts

  DeployQA:
    name: Deploy to Azure WebApp QA
    needs: build
    environment: QA
    runs-on: ubuntu-latest
    steps:
    # Downloading build artifact
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2
      continue-on-error: false
      with:
        name: buildartifacts
        path: buildartifacts
    # Uzipping build artifacts
    - name: unzipping build artifact
      run: |
        unzip -qq ./buildartifacts/Application.zip -d .

    # Login to azure
    - name: Login to Azure
      uses: azure/login@v1
      continue-on-error: false
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
     # Deploy web app on azure
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          
  deployPRD:
    name: Deploy to Azure WebApp PRD
    needs: [DeployQA]   
    environment: PROD
    runs-on: ubuntu-latest
    steps:
    # Downloading build artifact
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2
      continue-on-error: false
      with:
        name: buildartifacts
        path: buildartifacts
    # Uzipping build artifacts
    - name: unzipping build artifact
      run: |
        unzip -qq ./buildartifacts/Application.zip -d .
    # Deploy web app on azure
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME_PRD }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PRD}}